services:
  back-end:
    build: 
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:mysql://mysql-db/fullstack
      DB_USERNAME: example_user
      DB_PASSWORD: password123
    depends_on:
      - mysql-container
  front-end:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - back-end
    volumes:
      - webdata:/app/build/
  mysql-container:
    image: mysql:8.0.33-oracle
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: fullstack
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: example_user
      MYSQL_PASSWORD: password123
  web-server:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - webdata:/usr/share/nginx/html/data
#     - ./certbot/www/:/var/www/certbot/:ro
#     - ./certbot/conf/:/etc/letsencrypt/
    depends_on:
      - front-end
volumes:
  dbdata:
  webdata:
